"""Tests for Humanize sampling via SamplingSession.

Humanize = humanize=True. `bars` lists bars whose note skeleton (pitch/onset/
duration) is already fixed by the input score; only Velocity/microtiming
(Delta) tokens are regenerated by the model. Unlike infill, the target bars
are NOT hidden from the encoded prompt — only their expressive tokens are
withheld and deferred to the HumanizeStart/.../HumanizeEnd appendix.

The shared `ghost_tokenizer` fixture's encoder config does not have
supports_humanize=true, so this module builds its own tokenizer/model from a
copy of ghost_config with humanize enabled, keeping the shared fixtures (and
every other test module) untouched.
"""

from __future__ import annotations

import json

import pytest
import torch

import midigpt._core as _core
from midigpt._types import Score
from midigpt.attributes.base import AttributeAnalyzer
from midigpt.inference.config import (
    GenerationRequest,
    InferenceConfig,
    TrackPrompt,
)
from midigpt.inference.engine import InferenceEngine
from midigpt.inference.model.gpt2 import GPT2Config, GPT2LMHeadModel
from midigpt.inference.validation import RequestValidationError, validate_request
from midigpt.tokenizer.tokenizer import Tokenizer


@pytest.fixture
def humanize_tokenizer(ghost_config_json) -> Tokenizer:
    """Same structural config as `ghost_tokenizer`, with supports_humanize=true.

    ghost_config.json has no explicit "token_domains" list, so from_json()
    calls derive_token_domains() itself — flipping supports_humanize before
    parsing is enough to add the 5 Humanize token domains alongside every
    domain ghost already derives.
    """
    cfg_dict = json.loads(ghost_config_json)
    cfg_dict["supports_humanize"] = True
    cfg = _core.EncoderConfig.from_json(json.dumps(cfg_dict))
    analyzer = AttributeAnalyzer.from_config(cfg)
    return Tokenizer(cfg, analyzer)


@pytest.fixture
def humanize_model(humanize_tokenizer) -> GPT2LMHeadModel:
    torch.manual_seed(0)
    gpt2_cfg = GPT2Config(
        vocab_size=humanize_tokenizer.vocab_size(),
        n_positions=512,
        n_embd=16,
        n_layer=2,
        n_head=2,
    )
    model = GPT2LMHeadModel(gpt2_cfg)
    for p in model.parameters():
        if p.dim() >= 2:
            torch.nn.init.normal_(p, std=0.02)
    model.eval()
    return model


def _engine(humanize_model, humanize_tokenizer) -> InferenceEngine:
    return InferenceEngine(humanize_model, humanize_tokenizer, humanize_tokenizer._analyzer)


def _humanize_request(track_id: int, target_bars: list[int], **cfg_kw) -> GenerationRequest:
    base = dict(seed=0, max_attempts=3, novelty_check=False, silence_check=False)
    base.update(cfg_kw)
    return GenerationRequest(
        tracks=[TrackPrompt(id=track_id, bars=target_bars, humanize=True)],
        config=InferenceConfig(**base),
    )


def test_humanize_session_run_returns_score(humanize_model, humanize_tokenizer, simple_score):
    torch.manual_seed(0)
    engine = _engine(humanize_model, humanize_tokenizer)
    req = _humanize_request(track_id=0, target_bars=[2])
    result = engine.session(simple_score, req).run()
    assert isinstance(result, Score)
    assert len(result.tracks) == 1
    assert len(result.tracks[0].bars) == 4


def test_humanize_preserves_pitch_onset_duration_on_target_bar(
    humanize_model, humanize_tokenizer, simple_score
):
    """The skeleton (pitch/onset/duration) is fixed input, not a generation
    target — only Velocity/Delta may change."""
    torch.manual_seed(0)
    engine = _engine(humanize_model, humanize_tokenizer)
    # The result is resampled from model resolution to decode_resolution
    # (see Tokenizer.normalize_output), so scale the originals the same way
    # before comparing onset/duration.
    scale = humanize_tokenizer._vocab.config().decode_resolution / simple_score.resolution
    original = sorted(
        (n.pitch, round(n.onset_ticks * scale), round(n.duration_ticks * scale))
        for n in simple_score.tracks[0].bars[2].notes
    )

    req = _humanize_request(track_id=0, target_bars=[2])
    result = engine.session(simple_score, req).run()

    out = sorted(
        (n.pitch, n.onset_ticks, n.duration_ticks) for n in result.tracks[0].bars[2].notes
    )
    assert out == original


def test_humanize_preserves_unhumanized_bars(humanize_model, humanize_tokenizer, simple_score):
    torch.manual_seed(0)
    engine = _engine(humanize_model, humanize_tokenizer)
    scale = humanize_tokenizer._vocab.config().decode_resolution / simple_score.resolution
    original_bar0 = sorted(
        (n.pitch, round(n.onset_ticks * scale), round(n.duration_ticks * scale))
        for n in simple_score.tracks[0].bars[0].notes
    )
    original_bar3 = sorted(
        (n.pitch, round(n.onset_ticks * scale), round(n.duration_ticks * scale))
        for n in simple_score.tracks[0].bars[3].notes
    )

    req = _humanize_request(track_id=0, target_bars=[2])
    result = engine.session(simple_score, req).run()

    out_bar0 = sorted(
        (n.pitch, n.onset_ticks, n.duration_ticks) for n in result.tracks[0].bars[0].notes
    )
    out_bar3 = sorted(
        (n.pitch, n.onset_ticks, n.duration_ticks) for n in result.tracks[0].bars[3].notes
    )
    assert out_bar0 == original_bar0
    assert out_bar3 == original_bar3


def test_humanize_deterministic_with_fixed_seed(humanize_model, humanize_tokenizer, simple_score):
    engine = _engine(humanize_model, humanize_tokenizer)
    req = _humanize_request(track_id=0, target_bars=[1])

    torch.manual_seed(0)
    r1 = engine.session(simple_score, req).run()
    torch.manual_seed(0)
    r2 = engine.session(simple_score, req).run()

    n1 = [(n.pitch, n.onset_ticks, n.velocity) for b in r1.tracks[0].bars for n in b.notes]
    n2 = [(n.pitch, n.onset_ticks, n.velocity) for b in r2.tracks[0].bars for n in b.notes]
    assert n1 == n2


def test_humanize_does_not_mutate_input_score(humanize_model, humanize_tokenizer, simple_score):
    torch.manual_seed(0)
    engine = _engine(humanize_model, humanize_tokenizer)
    before = [
        [[(n.pitch, n.onset_ticks) for n in b.notes] for b in t.bars] for t in simple_score.tracks
    ]
    req = _humanize_request(track_id=0, target_bars=[2])
    engine.session(simple_score, req).run()
    after = [
        [[(n.pitch, n.onset_ticks) for n in b.notes] for b in t.bars] for t in simple_score.tracks
    ]
    assert before == after


# --------------------------------------------------------------------------- #
#  Validation: humanize/autoregressive/ignore mutual exclusivity + capability gate
# --------------------------------------------------------------------------- #


def test_humanize_and_ignore_mutually_exclusive(humanize_tokenizer, simple_score):
    req = GenerationRequest(tracks=[TrackPrompt(id=0, bars=[], humanize=True, ignore=True)])
    with pytest.raises(RequestValidationError, match="mutually exclusive"):
        validate_request(req, simple_score, humanize_tokenizer._vocab.config())


def test_humanize_and_autoregressive_mutually_exclusive(humanize_tokenizer, simple_score):
    req = GenerationRequest(
        tracks=[TrackPrompt(id=0, bars=[1], humanize=True, autoregressive=True)]
    )
    with pytest.raises(RequestValidationError, match="mutually exclusive"):
        validate_request(req, simple_score, humanize_tokenizer._vocab.config())


def test_humanize_requires_supports_humanize_capability(ghost_tokenizer, simple_score):
    """ghost_tokenizer's config has supports_humanize=false (the default)."""
    req = GenerationRequest(tracks=[TrackPrompt(id=0, bars=[1], humanize=True)])
    with pytest.raises(RequestValidationError, match="supports_humanize"):
        validate_request(req, simple_score, ghost_tokenizer._vocab.config())
